apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: observability
  description: @repo/observability
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  owner: platform
  system: monorepo-platform
